---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-api
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: users-api
  template:
    metadata:
      labels:
        deployment: users-api
    spec:
      containers:
      - name: users-api
        image: ghcr.io/snooyen/animal-facts/users-api:users
        imagePullPolicy: Always
        command:
          - users-api
          - --redisHost=redis-master
          - --redisPassword=$(REDIS_PASSWORD)
        ports:
        - containerPort: 3080
        - containerPort: 3081
        env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis
              key: redis-password

