---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fact-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: fact-admin
  template:
    metadata:
      labels:
        deployment: fact-admin
    spec:
      containers:
      - name: fact-admin
        image: ghcr.io/snooyen/animal-facts/fact-admin:main
        imagePullPolicy: Always
        command:
          - fact-admin
          - --port=3002
          - --redisHost=redis-headless
          - --redisPassword=$(REDIS_PASSWORD)
          - --twilioNumber=$(TWILIO_PHONE_NUMBER)
          - --adminNumber=$(ADMIN_PHONE_NUMBER)
        ports:
        - containerPort: 3002
        env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis
              key: redis-password
        - name: ADMIN_PHONE_NUMBER
          valueFrom:
            secretKeyRef:
              name: twilio
              key: adminNumber
        - name: TWILIO_PHONE_NUMBER
          valueFrom:
            secretKeyRef:
              name: twilio
              key: twilioNumber
        - name: TWILIO_ACCOUNT_SID
          valueFrom:
            secretKeyRef:
              name: twilio
              key: accountsid
        - name: TWILIO_AUTH_TOKEN
          valueFrom:
            secretKeyRef:
              name: twilio
              key: token
